server:
  port: ${sp.publish}
spring:
  application:
    name: ${sn.publish}
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: ${rocket-mq.name-server}
        bindings:
          output:
            producer:
              group: notifyGroup
              sync: true
      bindings:
        output:
          destination: notify
          content-type: application/json
# 开启MQ的日志
logging:
  level:
    com:
      alibaba:
        cloud:
          stream:
            binder:
              rocketmq: DEBUG